function raiseException(msg) {
    throw Error(msg);
}
